apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::319209208372:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-VDQR01QWYMAE
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::319209208372:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::319209208372:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-VDQR01QWYMAE\n  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n- rolearn: arn:aws:iam::319209208372:role/UdacityFlaskDeployCBKubectlRole\n  username: build\n  groups:\n    - system:masters\n","mapUsers":"[]\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2020-05-09T08:51:46Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"934","selfLink":"/api/v1/namespaces/kube-system/configmaps/aws-auth","uid":"d67eb2d8-51e1-424e-baac-2e4069375c07"}}
  creationTimestamp: "2020-05-09T08:51:46Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "18243"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d67eb2d8-51e1-424e-baac-2e4069375c07
